/**
 * Create by fay on 2018-10-17 18:49
 */
import React from 'react';

export default [
    {style:{}, type: 'blue-1', children: <>&nbsp;</>},
    {style:{}, type: 'blue-2', children: <>&nbsp;</>},
    {style:{}, type: 'blue-3', children: <>&nbsp;</>},
    {style:{}, type: 'blue-4', children: <>&nbsp;</>},
    {style:{}, type: 'blue-5', children: <>&nbsp;</>},
    {style:{}, type: 'blue-6', children: <>&nbsp;</>},
    {style:{}, type: 'blue-7', children: <>&nbsp;</>},
    {style:{}, type: 'blue-8', children: <>&nbsp;</>},
    {style:{}, type: 'blue-9', children: <>&nbsp;</>},
    {style:{}, type: 'blue-10', children: <>&nbsp;</>},

    {style:{}, type: 'purple-1', children: <>&nbsp;</>},
    {style:{}, type: 'purple-2', children: <>&nbsp;</>},
    {style:{}, type: 'purple-3', children: <>&nbsp;</>},
    {style:{}, type: 'purple-4', children: <>&nbsp;</>},
    {style:{}, type: 'purple-5', children: <>&nbsp;</>},
    {style:{}, type: 'purple-6', children: <>&nbsp;</>},
    {style:{}, type: 'purple-7', children: <>&nbsp;</>},
    {style:{}, type: 'purple-8', children: <>&nbsp;</>},
    {style:{}, type: 'purple-9', children: <>&nbsp;</>},
    {style:{}, type: 'purple-10', children: <>&nbsp;</>},

    {style:{}, type: 'cyan-1', children: <>&nbsp;</>},
    {style:{}, type: 'cyan-2', children: <>&nbsp;</>},
    {style:{}, type: 'cyan-3', children: <>&nbsp;</>},
    {style:{}, type: 'cyan-4', children: <>&nbsp;</>},
    {style:{}, type: 'cyan-5', children: <>&nbsp;</>},
    {style:{}, type: 'cyan-6', children: <>&nbsp;</>},
    {style:{}, type: 'cyan-7', children: <>&nbsp;</>},
    {style:{}, type: 'cyan-8', children: <>&nbsp;</>},
    {style:{}, type: 'cyan-9', children: <>&nbsp;</>},
    {style:{}, type: 'cyan-10', children: <>&nbsp;</>},

    {style:{}, type: 'green-1', children: <>&nbsp;</>},
    {style:{}, type: 'green-2', children: <>&nbsp;</>},
    {style:{}, type: 'green-3', children: <>&nbsp;</>},
    {style:{}, type: 'green-4', children: <>&nbsp;</>},
    {style:{}, type: 'green-5', children: <>&nbsp;</>},
    {style:{}, type: 'green-6', children: <>&nbsp;</>},
    {style:{}, type: 'green-7', children: <>&nbsp;</>},
    {style:{}, type: 'green-8', children: <>&nbsp;</>},
    {style:{}, type: 'green-9', children: <>&nbsp;</>},
    {style:{}, type: 'green-10', children: <>&nbsp;</>},

    {style:{}, type: 'magenta-1', children: <>&nbsp;</>},
    {style:{}, type: 'magenta-2', children: <>&nbsp;</>},
    {style:{}, type: 'magenta-3', children: <>&nbsp;</>},
    {style:{}, type: 'magenta-4', children: <>&nbsp;</>},
    {style:{}, type: 'magenta-5', children: <>&nbsp;</>},
    {style:{}, type: 'magenta-6', children: <>&nbsp;</>},
    {style:{}, type: 'magenta-7', children: <>&nbsp;</>},
    {style:{}, type: 'magenta-8', children: <>&nbsp;</>},
    {style:{}, type: 'magenta-9', children: <>&nbsp;</>},
    {style:{}, type: 'magenta-10', children: <>&nbsp;</>},

    {style:{}, type: 'pink-1', children: <>&nbsp;</>},
    {style:{}, type: 'pink-2', children: <>&nbsp;</>},
    {style:{}, type: 'pink-3', children: <>&nbsp;</>},
    {style:{}, type: 'pink-4', children: <>&nbsp;</>},
    {style:{}, type: 'pink-5', children: <>&nbsp;</>},
    {style:{}, type: 'pink-6', children: <>&nbsp;</>},
    {style:{}, type: 'pink-7', children: <>&nbsp;</>},
    {style:{}, type: 'pink-8', children: <>&nbsp;</>},
    {style:{}, type: 'pink-9', children: <>&nbsp;</>},
    {style:{}, type: 'pink-10', children: <>&nbsp;</>},

    {style:{}, type: 'red-1', children: <>&nbsp;</>},
    {style:{}, type: 'red-2', children: <>&nbsp;</>},
    {style:{}, type: 'red-3', children: <>&nbsp;</>},
    {style:{}, type: 'red-4', children: <>&nbsp;</>},
    {style:{}, type: 'red-5', children: <>&nbsp;</>},
    {style:{}, type: 'red-6', children: <>&nbsp;</>},
    {style:{}, type: 'red-7', children: <>&nbsp;</>},
    {style:{}, type: 'red-8', children: <>&nbsp;</>},
    {style:{}, type: 'red-9', children: <>&nbsp;</>},
    {style:{}, type: 'red-10', children: <>&nbsp;</>},

    {style:{}, type: 'orange-1', children: <>&nbsp;</>},
    {style:{}, type: 'orange-2', children: <>&nbsp;</>},
    {style:{}, type: 'orange-3', children: <>&nbsp;</>},
    {style:{}, type: 'orange-4', children: <>&nbsp;</>},
    {style:{}, type: 'orange-5', children: <>&nbsp;</>},
    {style:{}, type: 'orange-6', children: <>&nbsp;</>},
    {style:{}, type: 'orange-7', children: <>&nbsp;</>},
    {style:{}, type: 'orange-8', children: <>&nbsp;</>},
    {style:{}, type: 'orange-9', children: <>&nbsp;</>},
    {style:{}, type: 'orange-10', children: <>&nbsp;</>},

    {style:{}, type: 'yellow-1', children: <>&nbsp;</>},
    {style:{}, type: 'yellow-2', children: <>&nbsp;</>},
    {style:{}, type: 'yellow-3', children: <>&nbsp;</>},
    {style:{}, type: 'yellow-4', children: <>&nbsp;</>},
    {style:{}, type: 'yellow-5', children: <>&nbsp;</>},
    {style:{}, type: 'yellow-6', children: <>&nbsp;</>},
    {style:{}, type: 'yellow-7', children: <>&nbsp;</>},
    {style:{}, type: 'yellow-8', children: <>&nbsp;</>},
    {style:{}, type: 'yellow-9', children: <>&nbsp;</>},
    {style:{}, type: 'yellow-10', children: <>&nbsp;</>},

    {style:{}, type: 'volcano-1', children: <>&nbsp;</>},
    {style:{}, type: 'volcano-2', children: <>&nbsp;</>},
    {style:{}, type: 'volcano-3', children: <>&nbsp;</>},
    {style:{}, type: 'volcano-4', children: <>&nbsp;</>},
    {style:{}, type: 'volcano-5', children: <>&nbsp;</>},
    {style:{}, type: 'volcano-6', children: <>&nbsp;</>},
    {style:{}, type: 'volcano-7', children: <>&nbsp;</>},
    {style:{}, type: 'volcano-8', children: <>&nbsp;</>},
    {style:{}, type: 'volcano-9', children: <>&nbsp;</>},
    {style:{}, type: 'volcano-10', children: <>&nbsp;</>},

    {style:{}, type: 'geekblue-1', children: <>&nbsp;</>},
    {style:{}, type: 'geekblue-2', children: <>&nbsp;</>},
    {style:{}, type: 'geekblue-3', children: <>&nbsp;</>},
    {style:{}, type: 'geekblue-4', children: <>&nbsp;</>},
    {style:{}, type: 'geekblue-5', children: <>&nbsp;</>},
    {style:{}, type: 'geekblue-6', children: <>&nbsp;</>},
    {style:{}, type: 'geekblue-7', children: <>&nbsp;</>},
    {style:{}, type: 'geekblue-8', children: <>&nbsp;</>},
    {style:{}, type: 'geekblue-9', children: <>&nbsp;</>},
    {style:{}, type: 'geekblue-10', children: <>&nbsp;</>},

    {style:{}, type: 'lime-1', children: <>&nbsp;</>},
    {style:{}, type: 'lime-2', children: <>&nbsp;</>},
    {style:{}, type: 'lime-3', children: <>&nbsp;</>},
    {style:{}, type: 'lime-4', children: <>&nbsp;</>},
    {style:{}, type: 'lime-5', children: <>&nbsp;</>},
    {style:{}, type: 'lime-6', children: <>&nbsp;</>},
    {style:{}, type: 'lime-7', children: <>&nbsp;</>},
    {style:{}, type: 'lime-8', children: <>&nbsp;</>},
    {style:{}, type: 'lime-9', children: <>&nbsp;</>},
    {style:{}, type: 'lime-10', children: <>&nbsp;</>},

    {style:{}, type: 'gold-1', children: <>&nbsp;</>},
    {style:{}, type: 'gold-2', children: <>&nbsp;</>},
    {style:{}, type: 'gold-3', children: <>&nbsp;</>},
    {style:{}, type: 'gold-4', children: <>&nbsp;</>},
    {style:{}, type: 'gold-5', children: <>&nbsp;</>},
    {style:{}, type: 'gold-6', children: <>&nbsp;</>},
    {style:{}, type: 'gold-7', children: <>&nbsp;</>},
    {style:{}, type: 'gold-8', children: <>&nbsp;</>},
    {style:{}, type: 'gold-9', children: <>&nbsp;</>},
    {style:{}, type: 'gold-10', children: <>&nbsp;</>},

    {style:{}, type: 'black-1', children: <>&nbsp;</>},
    {style:{}, type: 'black-2', children: <>&nbsp;</>},
    {style:{}, type: 'black-3', children: <>&nbsp;</>},
    {style:{}, type: 'black-4', children: <>&nbsp;</>},
    {style:{}, type: 'black-5', children: <>&nbsp;</>},
    {style:{}, type: 'black-6', children: <>&nbsp;</>},
    {style:{}, type: 'black-7', children: <>&nbsp;</>},
    {style:{}, type: 'black-8', children: <>&nbsp;</>},
    {style:{}, type: 'black-9', children: <>&nbsp;</>},
    {style:{}, type: 'black-10', children: <>&nbsp;</>},
];